In [ ]:
# Jupyter Manhatten Distance Vectorized



In [1]:
import numpy as np

In [2]:
initial_state = np.array([[7, 2, 4], [5, 0, 6], [8, 3, 1]])
initial_state

array([[7, 2, 4],
       [5, 0, 6],
       [8, 3, 1]])

In [3]:
goal_state = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
goal_state

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
n, m = initial_state.shape
n

3

## Build the position matrix for initial_state

In [5]:
initPos = np.empty(n*m, dtype=int)
initPos # the values shown here are whatever was in memory

array([         0,          1,          0,         31,        952,
                0,        768,        139, 1718404984])

In [6]:
initPos[initial_state.reshape(n*m)] = np.arange(n*m, dtype=int)
initPos

array([4, 8, 1, 7, 2, 3, 5, 0, 6])

## Build the position matrix for goal_state

In [7]:
goalPos = np.empty(n*m, dtype=int)
goalPos

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
goalPos[goal_state.reshape(n*m)] = np.arange(n*m, dtype=int)
goalPos

array([0, 1, 2, 3, 4, 5, 6, 7, 8])


## Compute the Manhattan distance between the 2 position matrix

In [9]:
xInitPos, yInitPos = initPos%m, initPos//m
xGoalPos, yGoalPos = goalPos%m, goalPos//m

In [10]:
xInitPos

array([1, 2, 1, 1, 2, 0, 2, 0, 0], dtype=int32)

In [11]:
yInitPos

array([1, 2, 0, 2, 0, 1, 1, 0, 2], dtype=int32)

In [12]:
xGoalPos

array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int32)

In [13]:
yGoalPos

array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int32)

In [14]:
distance = np.abs(xInitPos-xGoalPos) + np.abs(yInitPos-yGoalPos)
distance

array([2, 3, 1, 2, 2, 2, 3, 3, 2], dtype=int32)

In [15]:
solution = distance[initial_state.reshape(n*m)].reshape((n,m))
solution

array([[3, 1, 2],
       [2, 2, 3],
       [2, 2, 3]], dtype=int32)